#!/usr/bin/env python3

import sys

from src.buscar_culpable import buscar_culpable
from src.helpers import parsear_archivo, serializar_pruebas

def main():
    if len(sys.argv) < 2:
        sys.exit(1)

    file_path = sys.argv[1]
    t, s = parsear_archivo(file_path)
    coincidencias = buscar_culpable(t, s)
    coincidencias_serializadas = serializar_pruebas(coincidencias)
    return coincidencias_serializadas

if __name__ == "__main__":
    print(main())

